import type {z} from 'zod';
import type * as s from './schema';
export type Catalog=z.infer<typeof s.catalogSchema>;
export type Dimension=z.infer<typeof s.dimension>;
export type Price=z.infer<typeof s.price>;
export type Shipping=z.infer<typeof s.shipping>;
export type Seller=z.infer<typeof s.seller>;
export type Product=z.infer<typeof s.product>;
export type Variant=z.infer<typeof s.variant>;
export type Offer=z.infer<typeof s.offer>;
export type Availability=Offer['availability'];
export type AdLink=z.infer<typeof s.adLink>;
export type Evidence=z.infer<typeof s.evidence>;
export type ImageRight=z.infer<typeof s.imageRight>;
export type CatalogRow={product:Product;variant:Variant;offer:Offer;seller:Seller};
